version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src  
    environment:
      - FLASK_APP=run.py
    command: ["python", "src/run.py"]

